[project]
name = "airflow-with-spark"
version = "0.1.0"
description = "Simple Airflow example involving PySpark"
requires-python = ">=3.13"
dependencies = [
    "apache-airflow>=3.1.3",
    "apache-airflow-providers-apache-spark>=5.3.4",
]
